import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { CaseStudiesClient } from "@/components/case-studies-client"

const allProjects = [
  {
    id: 18,
    title: "Nutrihealth Consult — Staff Management Platform",
    category: "CRM & Web System",
    image: "/nutrihealth-staff.png",
    link: "#",
    client: "Nutrihealth Consult",
    industry: "Health & Wellness",
    problem: "The company needed a central portal to manage their staff records, onboard new employees, and securely distribute documents like NDAs and promotional letters.",
    built: "A staff management platform featuring a central admin dashboard, employee directory, and automated document distribution for onboarding and internal communications.",
    result: "Staff onboarding time was cut in half, and the HR team now has a secure, organized system for tracking all employee documents and training progress.",
  },
  {
    id: 1,
    title: "Nutriticare",
    category: "CRM & Web System",
    image: "/nutriticare.png",
    link: "https://nutriticare.com/",
    client: "NutritiCare",
    industry: "Health & Wellness",
    problem: "The business needed a dedicated e-commerce platform to sell their natural herbal blends and wellness products directly to customers, moving away from manual WhatsApp orders.",
    built: "A comprehensive e-commerce store with an integrated shopping cart, product catalog for herbal teas and wellness products, and a streamlined checkout process. The platform also includes a blog and user accounts.",
    result: "Customers can now easily browse and purchase health products online 24/7. The automated e-commerce system handles orders seamlessly, significantly increasing sales volume and reducing manual administrative work.",
  },
  {
    id: 2,
    title: "MySkin Aesthetics — Clinic Management System",
    category: "CRM & Web System",
    image: "/myskinaeshetics.jpg",
    link: "https://www.myskinaestheticsclinic.com/",
    client: "MySkin Aesthetics Clinic",
    industry: "Health & Beauty",
    problem: "The clinic had no centralised system to manage bookings, client records, and treatment histories. Staff were relying on paper and personal phones.",
    built: "A clinic management website with appointment booking, client profiles, treatment tracking, and an admin dashboard for staff.",
    result: "Clinic bookings moved fully online. Staff no longer manage appointments manually. The site directly represents the brand's premium positioning.",
  },
  {
    id: 3,
    title: "Shushiman - Japanese Restaurant",
    category: "Web System",
    image: "/japanese.png",
    link: "https://japanese-restaurantt.netlify.app/",
    client: "Shushiman",
    industry: "Hospitality & Dining",
    problem: "The restaurant relied on phone calls and walk-ins for reservations, leading to double-bookings and a poor customer experience during peak hours.",
    built: "A custom restaurant management system with an interactive online menu, automated table reservation, and order management dashboard.",
    result: "Reduced booking errors to zero. Online reservations increased by 60%, and staff can now focus on serving customers instead of answering phones.",
  },
  {
    id: 4,
    title: "Regime - Dermatology Skincare",
    category: "CRM & Web System",
    image: "/regime.png",
    link: "https://regime-one.vercel.app/",
    client: "Regime Skincare",
    industry: "Health & Beauty",
    problem: "The clinic was struggling to manage patient records, treatment plans, and product sales efficiently across different branches.",
    built: "A unified patient management system integrating medical records, treatment scheduling, and an e-commerce storefront for skincare products.",
    result: "Streamlined operations across branches. Patient wait times reduced by 30%, and product sales increased due to the seamless online store integration.",
  },
  {
    id: 5,
    title: "Realtor - Real Estate Platform",
    category: "CRM & Web System",
    image: "/real-estate.png",
    link: "https://exc-real-estate-7.vercel.app/",
    client: "Excelsior Real Estate",
    industry: "Real Estate",
    problem: "Agents were tracking property listings and client interests on spreadsheets, making it difficult to match buyers with suitable properties quickly.",
    built: "A comprehensive real estate CRM with property listing management, automated client-property matching, and virtual tour integration.",
    result: "Property sales cycle shortened by 20%. Agents now have a centralized dashboard to track leads and manage property portfolios effectively.",
  },
  {
    id: 6,
    title: "HooBank - Fintech Platform",
    category: "UI/UX Design",
    image: "/banking.png",
    link: "https://modern-banking-website.vercel.app/",
    client: "HooBank Financial Services",
    industry: "Finance & Technology",
    problem: "The client needed a highly modern, trustworthy UI concept for their upcoming fintech platform to secure early investment and test user feedback.",
    built: "A high-fidelity interactive UI/UX prototype featuring modern banking dashboards, transaction flows, and a sleek, dark-mode focused aesthetic.",
    result: "The stunning prototype successfully communicated the product vision, helping the startup secure their pre-seed funding.",
  },
  {
    id: 7,
    title: "XORA - AI Video Editor",
    category: "Web System",
    image: "/xora.jpg",
    link: "https://xora-gold-delta.vercel.app/",
    client: "XORA Technologies",
    industry: "Media & Software",
    problem: "The startup required a high-performance landing page and user portal to showcase their AI-driven video editing capabilities and manage subscriptions.",
    built: "An interactive web platform with dynamic video previews, seamless subscription management, and a user-friendly account dashboard.",
    result: "Achieved a 45% conversion rate for new sign-ups. The platform effectively communicates the software's value proposition through interactive elements.",
  },
  {
    id: 8,
    title: "GPT-3 OpenAI",
    category: "UI/UX Design",
    image: "/gpt.png",
    link: "https://gptui.netlify.app/",
    client: "AI Solutions Initiative",
    industry: "Technology & AI",
    problem: "The team required an immersive landing page design to visually explain complex AI language model capabilities to non-technical users.",
    built: "A sleek, futuristic web design concept with vibrant gradients, interactive components, and clear typographical hierarchy.",
    result: "The conceptual design provided a clear visual direction for the engineering team and received highly positive feedback from initial user testing.",
  },
  {
    id: 9,
    title: "Fresh Coffee - Coffee Shop",
    category: "Web System",
    image: "/coffee.png",
    link: "https://cofee-shop-vert.vercel.app/",
    client: "Fresh Coffee Co.",
    industry: "Food & Beverage",
    problem: "The cafe lacked an online presence, relying entirely on foot traffic, and had no system for managing online pickup orders.",
    built: "A responsive e-commerce web application with a digital menu, integrated online ordering for pickup, and loyalty program tracking.",
    result: "Online orders now account for 25% of total daily revenue. Customer retention improved through the digital loyalty program.",
  },
  {
    id: 10,
    title: "Metaverse Explorer",
    category: "Web System",
    image: "/metaverse.png",
    link: "https://metaversuswebsite.netlify.app/",
    client: "Metaverse Ventures",
    industry: "Web3 & Technology",
    problem: "The client needed a visually immersive platform to explain their complex virtual reality offerings and capture lead information.",
    built: "A highly interactive, animation-rich website with 3D elements and a structured lead generation funnel for virtual real estate.",
    result: "Increased user time-on-site by 300%. The immersive design successfully translated complex concepts into engaging user experiences.",
  },
  {
    id: 11,
    title: "CarHub - Car Rental Design",
    category: "UI/UX Design",
    image: "/car-showcase.png",
    link: "https://car-showcase-sand.vercel.app/",
    client: "CarHub Rentals",
    industry: "Transportation & Logistics",
    problem: "The client needed a modern, visually appealing UI design for their car rental service to attract younger demographics before building out the backend.",
    built: "A high-fidelity web design featuring an intuitive car search interface, visual inventory showcase, and streamlined booking flow mockup.",
    result: "The new design effectively communicated the brand's modern aesthetic and served as the foundation for the upcoming full system development.",
  },
  {
    id: 12,
    title: "BrainWave - Possibilities of AI",
    category: "UI/UX Design",
    image: "/brainw.png",
    link: "https://brain-w.vercel.app/",
    client: "BrainWave AI",
    industry: "Technology & Education",
    problem: "A new AI educational platform needed a futuristic and engaging user interface to stand out in a crowded ed-tech market.",
    built: "A comprehensive UI/UX design system including a landing page mockup, course navigation UI, and immersive visual elements.",
    result: "The final design delivered a highly premium feel, setting a strong visual standard for the platform's upcoming development phase.",
  },
  {
    id: 13,
    title: "Smart-watch Sales Funnel",
    category: "Sales Funnel",
    image: "/smartwatch.jpg",
    link: "https://kindiestore.com.ng/s/q-smartwatch/",
    client: "Kindie Store",
    industry: "E-commerce",
    problem: "Product sales were happening through WhatsApp with no structured funnel or order management. Conversion from interest to payment was low.",
    built: "A high-converting product sales funnel with checkout flow, order confirmation, and WhatsApp follow-up integration.",
    result: "Structured checkout process in place. Drop-off reduced significantly compared to WhatsApp-only sales.",
  },
  { 
    id: 14, 
    title: "Timeless Watches Sales Funnel", 
    category: "Sales Funnel", 
    image: "/timeless.jpg",
    link: "https://kindiestore.com.ng/s/ww/",
    client: "Kindie Store",
    industry: "E-commerce",
    problem: "High-ticket luxury watches were seeing significant cart abandonment rates due to a complicated checkout process.",
    built: "A streamlined, single-page sales funnel with urgency triggers, simplified checkout, and automated abandoned cart recovery via WhatsApp.",
    result: "Cart abandonment reduced by 40%. The automated WhatsApp follow-ups successfully recovered 15% of lost sales.",
  },
  { 
    id: 15, 
    title: "Prosxact Product Sales Funnel", 
    category: "Sales Funnel", 
    image: "/prosxact.jpg",
    link: "https://kindiestore.com.ng/s/prosxact/", 
    client: "Kindie Store",
    industry: "E-commerce",
    problem: "The product launch required a dedicated high-converting page that could handle high traffic volumes and clearly articulate product benefits.",
    built: "A highly optimized, fast-loading sales funnel featuring video testimonials, clear value propositions, and seamless payment gateway integration.",
    result: "The funnel achieved a 4.5% conversion rate during the launch week, significantly outperforming previous standard product pages.",
  },
  { 
    id: 16, 
    title: "Juice-Extractor Sales Funnel", 
    category: "Sales Funnel", 
    image: "/juice.jpg",
    link: "https://kindiestore.com.ng/s/juicee/", 
    client: "Kindie Store",
    industry: "E-commerce",
    problem: "Marketing spend was being wasted on a generic product page that failed to demonstrate the practical benefits of the juice extractor.",
    built: "A focused sales funnel utilizing video demonstrations, customer reviews, and a clear, frictionless path to purchase.",
    result: "Return on Ad Spend (ROAS) improved by 2.5x. The focused funnel structure provided a much stronger narrative for the product.",
  },
]

const categories = ["All Work", "CRM & Web System", "UI/UX Design", "Sales Funnel"]

export default function Projects() {
  return (
    <>
      <Header />
      <main className="bg-gradient-to-b from-slate-900 via-slate-900 to-slate-950 min-h-screen">
        <CaseStudiesClient allProjects={allProjects} categories={categories} />
      </main>
      <Footer />
    </>
  )
}
